# Generated by Django 2.0 on 2018-01-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionGameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolapi.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semver', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField()),
                ('regional_tier_avg', models.CharField(max_length=255, null=True)),
                ('match_result_json', models.TextField(null=True)),
                ('match_timeline_json', models.TextField(null=True)),
                ('game_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolapi.GameVersion')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticGameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_icons_data_json', models.TextField()),
                ('items_data_json', models.TextField()),
                ('summonerspells_data_json', models.TextField()),
                ('runes_data_json', models.TextField()),
                ('champions_data', models.ManyToManyField(to='lolapi.ChampionGameData')),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolapi.GameVersion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField()),
                ('summoner_id', models.BigIntegerField()),
                ('latest_name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolapi.Region')),
            ],
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolapi.Region'),
        ),
        migrations.AddField(
            model_name='championgamedata',
            name='game_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolapi.GameVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('region', 'summoner_id'), ('region', 'account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='historicalmatch',
            unique_together={('match_id', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='championgamedata',
            unique_together={('game_version', 'champion')},
        ),
    ]
