# Generated by Django 2.0 on 2018-01-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionGameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolapi.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaticGameData',
            fields=[
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lolapi.GameVersion')),
                ('profile_icons_data_json', models.TextField()),
                ('items_data_json', models.TextField()),
                ('summonerspells_data_json', models.TextField()),
                ('runes_data_json', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='championgamedata',
            name='game_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolapi.GameVersion'),
        ),
        migrations.AddField(
            model_name='staticgamedata',
            name='champions_data',
            field=models.ManyToManyField(to='lolapi.ChampionGameData'),
        ),
        migrations.AlterUniqueTogether(
            name='championgamedata',
            unique_together={('game_version', 'champion')},
        ),
    ]
