# Generated by Django 2.0 on 2018-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='game_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='regional_tier_meta',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
