# Generated by Django 2.0 on 2018-01-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField()),
                ('regional_tier_avg', models.CharField(max_length=255)),
                ('match_result_json', models.TextField(null=True)),
                ('match_timeline_json', models.TextField(null=True)),
                ('game_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolapi.GameVersion')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField()),
                ('summoner_id', models.BigIntegerField()),
                ('latest_name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolapi.Region')),
            ],
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolapi.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('region', 'summoner_id'), ('region', 'account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='historicalmatch',
            unique_together={('match_id', 'region')},
        ),
    ]
