# Generated by Django 2.0.1 on 2018-01-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0002_auto_20180110_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatch',
            name='regional_tier_avg',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
