# Generated by Django 2.0.1 on 2018-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0003_summonertierhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonertierhistory',
            name='tiers_json',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
