# Generated by Django 2.0 on 2018-01-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0005_auto_20180117_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiotapiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_time', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lolapi.Region')),
            ],
        ),
    ]
