# Generated by Django 2.0 on 2018-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0007_auto_20180119_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='match_suppositions_json',
            field=models.TextField(null=True),
        ),
    ]
