# Generated by Django 2.0.1 on 2018-05-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0008_historicalmatch_match_suppositions_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmatch',
            old_name='match_suppositions_json',
            new_name='match_participants_histories_json',
        ),
    ]
